/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/**/*.{js,ts,jsx,tsx}',
    './src/index.html',
    '../../packages/session-processing/src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      {
        'guideai-light': {
          primary: '#0891b2',
          'primary-content': '#ffffff',
          secondary: '#059669',
          'secondary-content': '#ffffff',
          accent: '#0ea5e9',
          'accent-content': '#ffffff',
          neutral: '#475569',
          'neutral-content': '#ffffff',
          'base-100': '#ffffff',
          'base-200': '#f1f5f9',
          'base-300': '#e2e8f0',
          'base-content': '#0f172a',
          info: '#3b82f6',
          'info-content': '#ffffff',
          success: '#10b981',
          'success-content': '#ffffff',
          warning: '#f59e0b',
          'warning-content': '#000000',
          error: '#ef4444',
          'error-content': '#ffffff',
        },
      },
      {
        'guideai-dark': {
          primary: '#22d3ee',
          'primary-content': '#0c4a6e',
          secondary: '#34d399',
          'secondary-content': '#064e3b',
          accent: '#38bdf8',
          'accent-content': '#0c4a6e',
          neutral: '#64748b',
          'neutral-content': '#f1f5f9',
          'base-100': '#1e293b',
          'base-200': '#334155',
          'base-300': '#475569',
          'base-content': '#e2e8f0',
          info: '#60a5fa',
          'info-content': '#1e3a8a',
          success: '#4ade80',
          'success-content': '#14532d',
          warning: '#fbbf24',
          'warning-content': '#78350f',
          error: '#f87171',
          'error-content': '#7f1d1d',
        },
      },
      {
        'guideai': {
          primary: '#22d3ee',
          'primary-content': '#0c4a6e',
          secondary: '#34d399',
          'secondary-content': '#064e3b',
          accent: '#38bdf8',
          'accent-content': '#0c4a6e',
          neutral: '#64748b',
          'neutral-content': '#f1f5f9',
          'base-100': '#1e293b',
          'base-200': '#334155',
          'base-300': '#475569',
          'base-content': '#e2e8f0',
          info: '#60a5fa',
          'info-content': '#1e3a8a',
          success: '#4ade80',
          'success-content': '#14532d',
          warning: '#fbbf24',
          'warning-content': '#78350f',
          error: '#f87171',
          'error-content': '#7f1d1d',
        },
      },
    ],
    base: true,
    styled: true,
    utils: true,
  },
}